# Generated by Django 3.2.13 on 2022-04-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(null=True, upload_to='files/post')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
    ]
