# Generated by Django 3.2.13 on 2022-05-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post_app', '0006_auto_20220513_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='code_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
