# Generated by Django 3.2.13 on 2022-05-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post_app', '0007_video_code_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(default=True, null=True),
        ),
    ]
