# Generated by Django 3.2.13 on 2022-05-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post_app', '0008_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='code_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='slug',
            field=models.SlugField(default=True, null=True),
        ),
    ]
