# Generated by Django 4.0.3 on 2022-07-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post_app', '0011_auto_20220520_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaireaudio',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commentairevideo',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commentairevisuel',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='categorie',
            field=models.ManyToManyField(to='Post_app.categorie', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='document',
            name='categorie',
            field=models.ManyToManyField(to='Post_app.categorie', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='video',
            name='categorie',
            field=models.ManyToManyField(to='Post_app.categorie', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='visuel',
            name='categorie',
            field=models.ManyToManyField(to='Post_app.categorie', verbose_name='tags'),
        ),
    ]
