# Generated by Django 4.0.3 on 2022-07-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post_app', '0012_commentaireaudio_visible_commentairevideo_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='visuel',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
