# Generated by Django 3.2.13 on 2022-05-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='Student/profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_couverture',
            field=models.ImageField(default='default2.jpg', upload_to='Student/couverture'),
        ),
    ]
