# Generated by Django 4.0.4 on 2022-05-24 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Aucun titre', max_length=100)),
                ('desc', models.TextField(default='Pas de description', null=True)),
                ('type', models.CharField(choices=[('Reportage', 'Reportage'), ('Divertissement', 'Divertissement'), ('Science', 'Science')], default=('Science', 'Science'), max_length=255)),
                ('nbre_commentaire', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('link_audio', models.URLField()),
                ('code_id', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Visuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Aucun titre', max_length=100)),
                ('desc', models.TextField(default='Pas de description', null=True)),
                ('type', models.CharField(choices=[('Reportage', 'Reportage'), ('Divertissement', 'Divertissement'), ('Science', 'Science')], default=('Science', 'Science'), max_length=255)),
                ('nbre_commentaire', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('visuel', models.ImageField(upload_to='post/visuel')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('categorie', models.ManyToManyField(to='Post_app.categorie')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Aucun titre', max_length=100)),
                ('desc', models.TextField(default='Pas de description', null=True)),
                ('type', models.CharField(choices=[('Reportage', 'Reportage'), ('Divertissement', 'Divertissement'), ('Science', 'Science')], default=('Science', 'Science'), max_length=255)),
                ('nbre_commentaire', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('link_video', models.URLField()),
                ('code_id', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('categorie', models.ManyToManyField(to='Post_app.categorie')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Aucun titre', max_length=100)),
                ('desc', models.TextField(default='Pas de description', null=True)),
                ('type', models.CharField(choices=[('Reportage', 'Reportage'), ('Divertissement', 'Divertissement'), ('Science', 'Science')], default=('Science', 'Science'), max_length=255)),
                ('nbre_commentaire', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('doc', models.FileField(upload_to='post/file')),
                ('categorie', models.ManyToManyField(to='Post_app.categorie')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentaireVisuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visuel_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Post_app.visuel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentaireVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('video_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Post_app.video')),
            ],
        ),
        migrations.CreateModel(
            name='CommentaireAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('audio_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Post_app.audio')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='categorie',
            field=models.ManyToManyField(to='Post_app.categorie'),
        ),
        migrations.AddField(
            model_name='audio',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
