# Generated by Django 4.0.4 on 2022-05-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visuel',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
