# Generated by Django 4.0.4 on 2022-05-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post_app', '0002_alter_audio_type_alter_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='type',
            field=models.CharField(choices=[('Reportage', 'Reportage'), ('Divertissement', 'Divertissement'), ('Science', 'Science')], default='Science', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Reportage', 'Reportage'), ('Divertissement', 'Divertissement'), ('Science', 'Science')], default='Science', max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('Reportage', 'Reportage'), ('Divertissement', 'Divertissement'), ('Science', 'Science')], default='Science', max_length=255),
        ),
        migrations.AlterField(
            model_name='visuel',
            name='type',
            field=models.CharField(choices=[('Reportage', 'Reportage'), ('Divertissement', 'Divertissement'), ('Science', 'Science')], default='Science', max_length=255),
        ),
    ]
