# Generated by Django 4.0.3 on 2022-04-11 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Student/profile')),
                ('image_couverture', models.ImageField(upload_to='Student/couverture')),
                ('matricule', models.CharField(max_length=30, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('filiere', models.CharField(choices=[('IM', 'Internet et Multimédia'), ('GL', 'Génie Logiciel'), ('SI', 'Sécurité Informatique')], max_length=50)),
                ('annee', models.CharField(choices=[('L1', 'Licence1'), ('L2', 'Licence2'), ('L3', 'Licence3'), ('M1', 'Master1'), ('M2', 'Master2')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
