# Generated by Django 3.2.13 on 2022-05-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image_couverture',
        ),
        migrations.AlterField(
            model_name='student',
            name='filiere',
            field=models.CharField(blank=True, choices=[('IM', 'Internet et Multimédia'), ('GL', 'Génie Logiciel'), ('SI', 'Sécurité Informatique')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
