# Generated by Django 3.2.13 on 2022-05-16 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0003_visiteur_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='annee',
            field=models.CharField(choices=[('L1', 'Licence1'), ('L2', 'Licence2'), ('L3', 'Licence3'), ('M1', 'Master1'), ('M2', 'Master2'), ('D', 'Diplomé')], max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visiteur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visiteur', to=settings.AUTH_USER_MODEL),
        ),
    ]
