# Generated by Django 3.2.13 on 2022-05-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_auto_20220516_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_administrator',
            field=models.BooleanField(default=False),
        ),
    ]
