# Generated by Django 4.0.3 on 2022-07-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_student_is_administrator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_administrator',
        ),
    ]
